version: '3.8'
services:
  db:
    image: postgres:15
    container_name: banco_digital_db
    environment:
      POSTGRES_DB: banco_digital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"